
up: build
	docker compose up

build:
	./scripts/build_dev.sh

# default:
# 	./scripts/build_dev.sh
# 	./scripts/create_image_worker_dev.sh
# 	./scripts/create_image_manager_dev.sh
# 	docker compose up

down:
	docker compose down
